#!/bin/bash
export TTY

prefix="$1"

sed "s~^~$prefix~"

# I need a more stable way of doing this. Maybe use sed's e or r command
# Or a different command entirely
# Need a literal sed.

tf_prefixcontent="$(nix tf prefixcontent || echo /dev/null)"
trap "rm \"$tf_prefixcontent\" 2>/dev/null" 0

printf -- "%s\n" "$prefix" > "$tf_prefixcontent"

# for the purposes of prefixing things, sed appears to only be able to read from a file for 
# sed -e "N;/\n.*blah Blah/{r $tf_prefixcontent};P;D" AFile
