#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# apply-trim-untrim q " slkadfjldks jflkdsaj flkads     " | v

f="$1"
shift

for (( i = 1; i <= $#; i++ )); do
    eval ARG=\${$i}

    printf -- "%s" "$ARG" | sed -E 's/^(\s*).*/\1/'
    printf -- "%s" "$ARG" | sed -E 's/^\s*(.*[^[:space:]])\s*$/\1/' | eval "$f"
    printf -- "%s" "$ARG" | sed -E 's/^.*[^[:space:]](\s*)$/\1/'
done
