#!/bin/bash

# I should start creating libraries of such scripts but in a shell that
# always has functions imported:
# What language? clojure? common-lisp? choose common-lisp.

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

pager() {
    if is_tty; then
        less -rS $@
    else
        cat
    fi
}

opt="$1"
case "$opt" in
    list) {
        dpkg --get-selections | pager
        shift

        exit $?
    }
    ;;

    *)
esac

# dpkg --get-selections | v

/usr/bin/apt "$@"
