#!/bin/bash

__print_completions() {
    printf '%s\n' "${COMPREPLY[@]}"
}


# load bash-completion functions
# source /etc/bash_completion

# if ! shopt -oq posix; then
  # if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  # elif [ -f /etc/bash_completion ]; then
    # . /etc/bash_completion
  # fi
# fi


# load git's completion function
# _completion_loader git


CMD="$(cmd "$@")"


COMP_WORDS=($CMD)

COMP_LINE="$CMD"

COMP_POINT="$(printf -- "%s" "$VAR" "$CMD" | wc -c)"
COMP_POINT="$(( $COMP_POINT + 1 ))"

COMP_CWORD="$(printf -- "%s" "$VAR" "$CMD" | wc -w)"
COMP_CWORD="$(( $COMP_CWORD - 1 ))"

# _git
__print_completions