#!/bin/bash
export TTY

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

if is_tty; then
    exec 1> >(colorise-build-stdout.sh)
    exec 2> >(colorise-build.sh)
fi

# ( hs "$(basename "$0")" "$@" </dev/tty ` # Disable tty to pipe content into hs ` )
( hs "$(basename "$0")" "$@" 0</dev/null )

$HOME/.local/bin/cabal "$@"