#!/bin/bash
export TTY

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

pager() {
    if is_tty; then
        vs $@
    else
        cat
    fi
}

if test "$#" -eq "0"; then
    cmd="ci curl cheat.sh; rlwrap cheat.sh --shell"
    eval "$cmd"
else
    ci cheat.sh "$@" | strip-ansi | pager
fi