#!/bin/bash
export TTY

bot_name="CodeLingo Bot"
bot_email="hello@codelingo.io"

export GIT_AUTHOR_NAME="$bot_name"
export GIT_AUTHOR_EMAIL="$bot_email"
export GIT_COMMITTER_NAME="$bot_name"
export GIT_COMMITTER_EMAIL="$bot_email"

git commit --author="$bot_name <$bot_email>" "$@"