#!/bin/bash
cd $HOME/dump$HOME/notes2018/programs/dosbox
dosbox -conf "configs/keen.conf" \
    -c "mount c $HOME/dump$HOME/notes2018/programs/dosbox/c" \
    -c C: \
    -c "cd \DUKE2" \
    -c "mixer MASTER 20:20" \
    -c "NUKEM2.EXE \
    /JERK" -c "exit"