#!/bin/bash
export TTY

tf_pipe_buffer="$(exec 0<&-; nix tf pipe_buffer txt || echo /dev/null)"

cat > "$tf_pipe_buffer"

exec 3>&1

# export TTY; echo hi | eipe | cat

#if [ -n "$TTY" ]; then
#    # If used as vipe, this will need the environment variable TTY to work
#
#    lit "Attaching tty"
    exec 0<"$TTY"
    exec 1>"$TTY"
#else
#    # Otherwise, this probably has its own tty and only needs normal
#    # reattachment (maybe stdin was temporarily redirected)
#    exec </dev/tty
#fi

sp c "$tf_pipe_buffer"

exec 1>&3

cat "$tf_pipe_buffer"

trap "rm $(aq "$tf_pipe_buffer") 2>/dev/null" 0

# This will kill the emacs server. I need to implement an emacs vipe myself.
# echo hi | EDITOR=sp vipe
