#!/bin/bash
export TTY

# I need to make 'unescape'

# similar to bs but does not escape backslash as well

chars="$1"
: ${chars:=" "}
chars="$(printf -- "%s" "$chars" | qne)"

sed "s_\\([$chars]\\)_\\\\\\1_g"
# sed 's_\([$chars]\)_\\\1_g'
