#!/bin/bash
export TTY

# py i sqlparse

IFS= read -rd '' input < <(cat /dev/stdin)

tf_sql="$(nix tf sql sql || echo /dev/null)"
trap "rm \"$tf_sql\" 2>/dev/null" 0

printf -- "%s\n" "$input" > "$tf_sql"

sqlformat --reindent --keywords upper --identifiers lower "$tf_sql"

# cat "$tf_sql"