#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -n) {
        LINES="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

# eval `resize`

umn | awk 1 | while IFS=$'\n' read -r line; do
    if [ -f "$line" ]; then
        if test -n "$LINES"; then
            head -n $LINES "$line"
        else
            cat "$line"
        fi
    elif [ -d "$line" ]; then
        # echo "$line"
        dirinfo "$line" | xsv table
        # echo
        # ls "$line"
    else
        echo "$line"
    fi
done
