#!/bin/bash
export TTY

awk 1 | umn | sed 's#/$##' | while IFS=$'\n' read -r line; do
    if [ -d "$line" ]; then
        dls "$line" | sed "s#^#$line/#"
    elif [ -f "$line" ]; then
        cat "$line"
    fi
done | mnm | tm -f -i nw -noerror "fzf -nm"