#!/bin/bash
export TTY

cd "$(vc get-top-level)" && pwd

id="$(prs-tiles-and-urls | fzf | s field 1 | sed -n 's/.*[^0-9]\([0-9]\+\)$/\1/p')"
echo "Selected: PR $id" 1>&2

if [ -n "$id" ]; then
    hub pr checkout "$id"

    go-to-dir-of-change
fi