#!/bin/bash
export TTY

pattern="$1"
pattern="$(p "$pattern" | c anum | c lc)"

CMD="$(
for (( i = 1; i < $#; i++ )); do
    eval ARG=\${$i}
    printf -- "%s" "$ARG" | qne
    printf ' '
done
eval ARG=\${$i}
printf -- "%s" "$ARG" | qne
)"

stdin_exists() {
    ! [ -t 0 ]
}

filter() {
    $HOME/source/git/fzf/bin/fzf --no-sort -f "$pattern" 2>/dev/null

    return 0
}

if stdin_exists; then
    cat | filter
else
    paths="$(eval "lit $CMD")" # expand
    lit "$paths" | awk 1 | while read -r line; do
        if [ -n "$line" ] && [ -f "$line" ]; then
            cat "$line"
        fi
    done | filter
fi