#!/bin/bash

( hs "$(basename "$0")" "$@" </dev/tty ` # Disable tty to pipe content into hs ` )

gitfolder="$MYGIT"

# TODO
# * Make an option within this script to set up this script
# sudo npm install -g download-gist
# * Make this script download gists

stdin_exists() {
    ! [ -t 0 ]
    # ! [ -t 0 ] && read -t 0
}

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

is_tty && DROP_TO_SHELL=y

disable_stdin=y
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -notty) {
        DROP_TO_SHELL=n
        shift
    }
    ;;

    -i) {
        disable_stdin=n
        shift
    }
    ;;

    -s) {
        export SHALLOW=y
        shift
    }
    ;;

    -p) {
        PRINT_DIRS=y
        shift
    }
    ;;

    -cl|-clone) {
        # Side-effects only
        NO_CLONE=n
        shift
    }
    ;;

    -nc|-noclone) {
        # Side-effects only
        NO_CLONE=y
        shift
    }
    ;;

    -nn|-nonotify) {
        NO_NOTIFY=y
        export LIGHT=y # Don't smash the github API
        shift
    }
    ;;

    *) break;
esac; done

# # This doesn't work, sadly
# Also, it maybe breaks when I actually want to use stdin
# if test "$disable_stdin" = "y"; then
#     eval 0<&-
# fi

stdin_exists && DROP_TO_SHELL=n

export NO_CLONE SHALLOW NO_NOTIFY

{
    stdin_exists && awk1

    # send arguments to stdin
    test "$#" -gt 0 && pl "$@"
} | gh-url-to-dir | {
    if test "$PRINT_DIRS" = "y"; then
        cat
        exit 0
    fi

    lastclonedrepo="$(tail -n 1 | umn)"

    # cd "$lastclonedrepo"

    if ! test "$NO_NOTIFY" = "y"; then
        printf -- "%s" "$lastclonedrepo" | xc -m &>/dev/null
    fi

    if ! test "$NO_NOTIFY" = "y"; then
        ns "$lastclonedrepo" &>/dev/null 0</dev/null # This must have dev null or the next pipe will break
    fi

    if ! test -d "$lastclonedrepo"; then
        lit "repo not created $lastclonedrepo" 1>&2
    else
        ( cd "$lastclonedrepo"; github-add-upstream 1>&2; )
    fi

    if test "$DROP_TO_SHELL" = "y" && test -d "$lastclonedrepo"; then
        exec </dev/tty # why does this break the tty? Darn it, it's needed. # IDK. it appeared last time to break the terminal. confirm
        # bash
        cd "$lastclonedrepo"

        # tm -d sph -c "$lastclonedrepo" ranger # This is annoying

        CWD="$lastclonedrepo" zsh
    else
        printf -- "%s\n" "$lastclonedrepo"
    fi
}