#!/bin/bash
export TTY

! is-git && exit 1

cd "$(vc get-top-level)" && pwd

url="$(vc url)"

rp="$(realpath ".")"
dnbn="$(basename "$rp")"

cd ..
git clone "${url}.wiki"
cd "${dnbn}.wiki"

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

if is_tty; then
    zcd .
else
    pwd
fi
