#!/bin/bash
export TTY

dp="$(git diff --name-only | head -n 1 | u dn | u rp)"
if [ -z "$dp" ]; then
    dp="$(git diff --name-only HEAD\^! | add-prefix "$(vc root)/" | head -n 1 | u dn | u rp)"
fi

if [ -n "$dp" ]; then
    echo "$dp"
    cd "$dp"
    CWD="$dp" zsh
else
    echo "No files changed unstaged or HEAD\^!" 1>&2
fi