#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "# <==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

cmd="$1"

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

pager() {
    if is_tty; then
        v
    else
        cat
    fi
}

hsq "$cmd" | xa cat1 | tac | pager
