#!/bin/bash
export TTY

IFS= read -rd '' input < <(cat /dev/stdin)

tf_temp="$(nix tf temp || echo /dev/null)"
trap "rm \"$tf_temp\" 2>/dev/null" 0

printf -- "%s" "$input" > "$tf_temp"

bulleted-string-to-nested-list.rkt "$tf_temp"
