#!/bin/bash
export TTY

# Internet search

opt="$1"
shift
case "$opt" in
    searchcode.com) {
        code="$(cat)"

        tm n "$f :: NOT IMPLEMENTED"
        {
            lit "NOT IMPLEMENTED"
            lit "$code" | unesc
        } | less

        # Search searchcode for the code

        # xsearchcode.sh
        :
    }
    ;;

    template) {
        :
    }
    ;;

    *)
esac
