#!/bin/bash
cd $HOME/dump$HOME/notes2018/programs/dosbox
# -fullscreen
dosbox -conf "configs/keen.conf" -c "mount c $HOME/dump$HOME/notes2018/programs/dosbox/c" -c C: -c "cd \KEEN" -c "mixer MASTER 20:20" -c "KEEN4E.EXE /JERK" -c "exit"
#dosbox -conf "configs/keen.conf" -c "mount c $HOME/computer/programs/dosbox/c" -c C: -c "cd \KEEN410" -c "mixer MASTER 20:20" -c "KEEN4E.EXE /JERK" -c "exit"