#!/bin/bash
cd $HOME/dump$HOME/notes2018/programs/dosbox
# -fullscreen
dosbox -conf "configs/keen.conf" -c "mount c $HOME/dump$HOME/notes2018/programs/dosbox/c" -c C: -c "cd \keen3" -c "mixer MASTER 20:20" -c "KEEN3.EXE" -c "exit"