#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" 0</dev/null ) &>/dev/null

# Make connections unlimited. This fixes kubefwd because kubefwdd uses kubectl
# --streaming-connection-idle-timeout=0 

/usr/bin/kubectl "$@"
