#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "#" <== "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

query="$1"
encoded_query="$(p "$query" | urlencode)"

# Ensure I can search throuh these package managers
# apt
# pip (Python)
# _ (Go) -- Use google to search for go packages. Dep works on URLs for found packages only.
# raco (Racket)

# ocaml
# Rust
# Node
# Haskell
# Clojure

{
    echo "* apt"
    apt-cache search "$query"
    echo

    echo "* opam (ocaml)"
    opam search "$query"
    echo

    echo "* pip"
    echo "REMEMBER: pip-show-contents <library>"
    pip search "$query"
    echo

    echo "* go"
    elinks-dump "https://go-search.org/search?q=$encoded_query" | sed -n '/^\s\+[0-9]/{p;n;p;n;p}' | s efs
    echo

    echo "* raco"
    # Scrape this somehow
    # elinks-dump "https://pkgd.racket-lang.org/pkgn/search?q=google" | v
    curl "https://pkgd.racket-lang.org/pkgn/search?q=$encoded_query" | xurls | grep /package/
    echo

    echo "* rust"
    cargo search "$query"
    echo
} | pager