#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

declare -a names
declare -a parts
declare i=0

names=("$@")
name="$1"
while x=$(dirname "$name"); [ "$x" != "/" ]
do
    parts[$i]="$x"
    i=$(($i + 1))
    name="$x"
done

for prefix in "${parts[@]}" /
do
    for name in "${names[@]}"
    do
        if [ "${name#$prefix/}" = "${name}" ]
        then continue 2
        fi
    done
    echo "$prefix"
    break
done
