#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" </dev/tty ` # Disable tty to pipe content into hs ` )

# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# options might include
# - ignore .git -- default true
# - copy depth -- default 1


fn1="$1"
fn2="$2"

td_dir1="$(mktemp -t -d td_med_dir_A_XXXXXX | si +med dirA || echo /dev/null)"
trap "rmdir \"$td_dir1\" 2>/dev/null" 0

td_dir2="$(mktemp -t -d td_med_dir_B_XXXXXX | si +med dirB  || echo /dev/null)"
trap "rmdir \"$td_dir1\" 2>/dev/null" 0

cp -L "$fn1" "$td_dir1/file.dat"
cp -L "$fn2" "$td_dir2/file.dat"

dirdiff "$td_dir1" "$td_dir2"
