#!/bin/bash
export TTY

sha1="$1"

locate -r '\.git$' | awk 1 | while IFS=$'\n' read -r line; do
    if [ -d "$line" ]; then
        cd "$line"
        if git-commit-exists "$sha1"; then
            git show "$sha1"
            exit 0
        fi
    fi
done
exit 0
