#!/bin/bash
export TTY

# All things navigation. Changing directory in zsh to and from dump for
# example

# What about nix?
# What about new?
# Why navigation?

: ${CWD:="$(pwd)"}; cd "$CWD"

# This determines the actual shell that runs this script. But what about
# the shell this script is run from? Need to expont.
# readlink /proc/$$/exe

opt="$1"
shift
case "$opt" in
    menu) {
        # tm n "$opt :: NOT FULLY IMPLEMENTED"
        if lit "$CWD" | grep -q -P "^$DUMP"; then
            ndir="$(p "$CWD" | sed "s=^$DUMP==")"
            mkdir -p "$ndir"
            cd "$ndir"
            CWD="$ndir" $SHELL
        else
            ndir="$(p "$CWD" | sed "s=^=$DUMP=")"
            mkdir -p "$ndir"
            cd "$ndir"
            CWD="$ndir" $SHELL
        fi
    }
    ;;

    template) {
        :
    }
    ;;

    *)
esac
