#!/bin/bash
export TTY

# This script is misnamed

# nvt -2 man less
# nvt -2 elinks "http://news.ycombinator.com"

EVAL=n
precmd=
postcmd=
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -2) {
        # precmd="TERM=xterm-2color "
        precmd="export TERM=screen-2color; "
        # precmd="TERM=vt100 "
        shift
    }
    ;;

    -pak|-w) {
        postcmd="; pak"
        shift
    }
    ;;

    -E) {
        EVAL=y
        shift
    }
    ;;

    *) break;
esac; done

CMD="$(cmd "$@")"

if test $# -eq 0; then
    CMD="\"zsh\""
fi


if test "$EVAL" = "y"; then
    CMD="eval $CMD"
fi

export INSIDE_NEOVIM=y
export NO_DEFAULT_BG=y # This is so any script that uses colorize-build looks better inside neovim

if which -a nvim &>/dev/null; then
    cmd="nvim -u $HOME/.nvimrc -c $(aqf "call TermAndQuit($(aqf "$precmd $CMD$postcmd"))") -c $(aqf "call GeneralSyntax()") -c $(aqf "call NumberSyntax()") -c $(aqf "normal! i")"
    eval "$cmd"
else
    eval "$CMD"
fi