#!/bin/bash
export TTY

# This script is misnamed

# nvt -2 man less
# nvt -2 elinks "http://news.ycombinator.com"

# nvt does not change the *inner* tmux's TERM environment variable

EVAL=n
precmd=
wd=
pak=
ttype=vt100
while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -2) { ttype=2; shift; }; ;;
    -b+w) { ttype=b+w; shift; }; ;;
    -vt100) { ttype=vt100; shift; }; ;;

    -E) {
        EVAL=y
        shift
    }
    ;;

    -c) {
        wd="$2"
        shift
        shift
    }
    ;;

    -pak) {
        pak=y
        shift
    }
    ;;

    *) break;
esac; done

case "$ttype" in
    -2) {
        # precmd="TERM=xterm-2color "
        precmd="export TERM=screen-2color; "
        # precmd="TERM=vt100 "
    }
    ;;

    vt100) { precmd="export TERM=vt100; "; }; ;;
    b+w) { precmd="export TERM=xterm-2color; "; shift; }; ;;

    *)
esac

# set -- "TERM=vt100 "$@"

CMD="$(cmd "$@")"

# echo "$@ $#" | tv

if test $# -eq 0; then
    CMD="\"zsh\""
fi

displayedname() {
    echo -n "[ "
    sed 's/^.*-//'
    echo -n " ]  "
}

if test "$EVAL" = "y"; then
    CMD="eval $CMD"
fi

if test "$pak" = "y"; then
    CMD+="; pak"
fi

# I need 2 tmux sessions. One nested in the other
# One session to provide 2 windows. This is the parent session
#   One window will have a neovim containing a tmux attach to the child session. 
#   The other window will have a tmux attach to the child session.

# Perhaps I should make q escape the $
# Don't use the session_id because of the $. Instead, use the name
child_session_name="$(tmux new -s "$(uuidgen)" -F "#{session_name}" -P -d -n "protected" "$CMD")" # holds the program
tmux set -t "$child_session_name" status-left "$(printf -- "%s" "$child_session_name" | displayedname)"

if [ -z "$child_session_name" ]; then
    exit 0
fi

parent_session_name="$(tmux new -s "$(uuidgen)" -F "#{session_name}" -P -d -n "normal" "TMUX= tmux attach -t '${child_session_name}:'")" # holds the child in 2 different windows
tmux set -t "$parent_session_name" status-left "$(printf -- "%s" "$parent_session_name" | displayedname)"

if [ -n "$parent_session_name" ]; then
    # Even with single quotes here, the $ sign was breaking it
    # somewhere. So use uuidgen
    cmd="nvim -u $HOME/.nvimrc -c $(aqf "call TermAndQuit($(aqf "$precmd tmux attach -t ${child_session_name}:"))") -c $(aqf "call GeneralSyntax()") -c $(aqf "call NumberSyntax()") -c $(aqf "normal! i")"
    # echo "$cmd" | tv
    tmux neww -t "${parent_session_name}:" -n "nv" "$cmd"
fi

TMUX= tmux attach -t "${parent_session_name}:"

# Need ' with eval because session ids have $
# eval "TMUX= tmux attach -t '\"${parent_session_id}:\"'"