#!/bin/bash
export TTY

fp="$1"
fn=$(basename "$fp")
dn=$(dirname "$fp")
ext="${fn##*.}"
mant="${fn%.*}"
shift

# This worked! for the brady bunch
yt="$(p "$fp" | sed -n '/youtube.com/p')"
if [ -n "$yt" ]; then
    ext=yt
fi

echo
printf -- "%s\n" "$mant" | hls -i -b dgrey -f yellow ".*"
case "$ext" in
    webm|mp4|mkv) {
        vlc "$fp" &>/dev/null
    }
    ;;

    yt) { # this is a youtube url
        yt -v "$(p "$fp" | xurls | head -n 1)"
    }
    ;;

    *)
esac
