#!/bin/bash

# I should be able to cat into vd
# There should be no errors. vd might already be ok.

# It still doesn't treat piped input particularly well I should extend
# vd

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -2) {
        # precmd="TERM=xterm-2color "
        precmd="export TERM=screen-2color; "
        # precmd="TERM=vt100 "
        shift
    }
    ;;

    *) break;
esac; done

python3.6 $HOME/source/git/saulpw/visidata/bin/vd "$@"