#!/usr/bin/python2
# EASY-INSTALL-ENTRY-SCRIPT: 'py2hy==0.8.0','console_scripts','py2hy'
__requires__ = 'py2hy==0.8.0'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('py2hy==0.8.0', 'console_scripts', 'py2hy')()
    )
