#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" # <== "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

pager() {
    if is_tty; then
        vs $@
    else
        cat
    fi
}

export PYTHONSTARTUP= 

/usr/bin/pydoc "$@" 2>/dev/null | pager