#!/bin/bash
export TTY

# resolve paths

awk 1 | while IFS=$'\n' read -r fp; do
    if [ -e "$fp" ]; then
        rp="$(realpath "$fp")"
        printf -- "%s\n" "$rp"
    else
        bn="$(which "$fp")"
        if test "$?" -eq 0; then
            printf -- "%s\n" "$fp"
        fi
    fi
done
