#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import spacy

text = sys.stdin.read()

nlp = spacy.load("en")

#doc = nlp(unicode(text, "utf-8")) # py2
doc = nlp(str(text))
for span in doc.sents:
    print(str(span))
    #  print("#> span:", span)
