#!/bin/bash
export TTY

selection="$(cat directories.* | mnm | fzf | umn)"

is_tty() {
    # If stout is a tty
    [[ -t 1 ]]
}

if [ -n "$selection" ]; then
    dir="$(printf -- "%s" "$selection" | u rp)"

    if ! is_tty; then
        printf -- "%s\n" "$dir"
    else
        cd "$dir"
        clear
        export CWD="$dir"
        zsh
    fi
fi
