#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
m  magit
M  magithub
e  emacs
s  spacemacs
HEREDOC

echo "$0" | udl
echo "$options"

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    m) cmd="magit" ;;
    M) cmd="magithub" ;;
    e) cmd="e" ;;
    s) cmd="sp" ;;
esac
echo
echo "$cmd"
eval "$cmd"
