#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

d="$(basename "$(pwd)")"
nd="${d}_$(k f8)"
bcmd="cd ..; yn && rs --remove-source-files $(aqf "$d/") $(aqf "$nd"); CWD=$(aqf "$(pwd)") zsh"

read -r -d '' options <<HEREDOC
.  EDIT
b  $bcmd
t  bundle-dir
HEREDOC

echo "$0" | udl
echo "$options" | mnm

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    b) cmd="$bcmd" ;;
    t) cmd="bundle-dir" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"