#!/bin/bash
export TTY

clear

fzf-dirs-cd-deep() {
    # sel="$(F d | u bn | fzf | mnm)"
    sel="$(F d | mnm | fzf)"

    if [ -n "$sel" ]; then
        dir="$(printf -- "%s" "$sel" | umn | u rp)"
        p "$dir" | mnm | xc -n -i
        cd "$dir"
        CWD="$dir" zsh
    fi
}

fzf-dirs-cd() {
    sel="$(F find-dirs-here | fzf)"

    if [ -n "$sel" ]; then
        dir="$(printf -- "%s" "$sel" | umn | u rp)"
        p "$dir" | mnm | xc -n -i
        cd "$dir"
        CWD="$dir" zsh
    fi
}

# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
s  scripts
S  fzf-dirs-cd-deep
b  blog
h  programs/hs
E  $EMACSD
n  notes
v  vars
m  music    
k  sh-commands
N  programs/ns
1  cd CWD=$HOME/go/src/github.com/codelingo zsh
8  notes2018
7  notes2018
r  notes/scratch
f  go-to-dir-of-change
F  go-to-dir-of-important-change
R  select-recent-dir
o  notes/ws
c  croogle
G  ranger $HOME/go/src/github.com
e  /etc
;  go-to-dir-of-unstaged-changes
w  /var/www
2  /var/www/gallery
t  $DUMP/torrents
T  new temp folder
C  temp git repo from here
^? tm-shortcuts
d  $DUMP
D  $BULK/downloads
/  /
h\`  ~ home
g  sh-git-dir
z  sh-fuzzy-dir
O  sh-dir-ws
HEREDOC

echo "$0" | udl
echo "$options"

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    n) cmd="zcd $NOTES" ;;
    v) cmd="zcd $NOTES/vars" ;;
    b) cmd="CWD=$MYGIT/mullikine/mullikine.github.io zsh" ;;
    h) cmd="CWD=$HOME/notes2018/programs/hs zsh" ;;
    E) cmd="zcd $MYGIT/config/emacs" ;;
    8) cmd="CWD=$HOME/notes2018 zsh" ;;
    7) cmd="CWD=$HOME/notes2017 zsh" ;;
    m) cmd="CWD=$HOME/notes2018/ws/music zsh" ;;
    N) cmd="CWD=$HOME/notes2018/programs/ns zsh" ;;
    s) cmd="CWD=$HOME/scripts zsh" ;;
    r) cmd="CWD=$NOTES/scratch zsh" ;;
    f) cmd="go-to-dir-of-change" ;;
    \;) cmd="go-to-dir-of-unstaged-changes" ;;
    F) cmd="go-to-dir-of-important-change" ;;
    R) cmd="select-recent-dir" ;;
    o) cmd="zcd $NOTES/ws" ;;
    d) cmd="zcd $DUMP" ;;
    D) cmd="zcd $BULK/downloads" ;;
    O) cmd="sh-dir-ws" ;;
    e) cmd="CWD=/etc zsh" ;;
    S) cmd="fzf-dirs-cd-deep" ;;
    w) cmd="CWD=/var/www zsh" ;;
    G) cmd="CWD=$HOME/go/src/github.com ranger $HOME/go/src/github.com" ;;
    2) cmd="CWD=/var/www/gallery zsh" ;;
    c) cmd="CWD=/var/www/croogle zsh" ;;
    t) cmd="CWD=$DUMP/torrents zsh" ;;
    T) cmd="new-temp-folder" ;;
    C) cmd="tg ." ;;
    1) cmd="CWD=$HOME/go/src/github.com/codelingo zsh" ;;
    /) cmd="CWD=/ zsh" ;;
    h|\`) cmd="CWD=$HOME zsh" ;;
    g) cmd="sh-git-dir" ;;
    ) cmd="tm-shortcuts" ;;
    z) cmd="sh-fuzzy-dir" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"
