#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
r  remember.org
t  todo.org
g  glossary.txt
p  perspective.org
P  plan.org
k  keep-in-mind.org
n  need.org
f  files.txt
e  examples.txt # fuzzy search this
HEREDOC

echo "$0" | udl
echo "$options" | mnm

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    r) cmd="v $HOME/notes2018/remember.org" ;;
    t) cmd="v $HOME/notes2018/todo.org" ;;
    g) cmd="v $HOME/notes2018/glossary.txt" ;;
    p) cmd="v $HOME/notes2018/perspective.org" ;;
    P) cmd="v $HOME/notes2018/plan.org" ;;
    k) cmd="v $HOME/notes2018/keep-in-mind.org" ;;
    n) cmd="v $HOME/notes2018/need.org" ;;
    f) cmd="v $HOME/notes2018/files.txt" ;;
    e) cmd="v $HOME/notes2018/examples.txt" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"