#!/bin/bash
export TTY

# exec 1> >(mnm)

# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

# Select a directory from a decision tree

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
HEREDOC

eval `resize`

echo "$0" | udl
{
    echo "$options"
    wfind . -type d | head -n "$(bc <<< "$LINES / 2")"
} | mnm

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    d) cmd="sh-dir" ;;
    P) cmd="CWD=$(aqf $(pwd -P)) zsh" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"
