#!/bin/bash
export TTY

# links
# https://www.mankier.com/1/kubectl-exec

clear
# exec 1> >(mnm)

read -r -d '' options <<HEREDOC
.  EDIT
x https://www.mankier.com/1/kubectl-exec
HEREDOC

echo "$0" | udl
echo "$options"

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    x) { cmd="pl https://www.mankier.com/1/kubectl-exec | xc -i"; }; ;;
    
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"