#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
.  EDIT
h  htop
d  sh-docker
i  iotop
s  s-tui
f  fix-lag.sh
IF  iftop
E  show-extensions-below | xsv table
HEREDOC

echo "$0" | udl
echo "$options"

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    h) cmd="htop" ;;
    d) cmd="sh-docker" ;;
    s) cmd="s-tui" ;;
    i) cmd="sudo iotop" ;;
    f) cmd="fix-lag.sh" ;;
    # I|F) cmd="sudo iftop -i wlp3s0" ;;
    I|F) cmd="sudo iftop -i wlan0" ;;
    E) cmd="show-extensions-below | xsv table" ;;

esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"
