#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

page="$1"

if test -z "$page"; then
    read -p page:  -r page
fi

test -z "$page" && exit 1

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
h  tm -d sph "m u $page"
v  tm -d spv "m u $page"
nw tm -d nw "m u $page"
p  tm -d rs "m u $page"
e  tm -d rs "eman $page"
W  tm -d rs "woman $page"
HEREDOC

echo "$0" | udl
echo "$options" | mnm

read -n1 d
# clear

case "$d" in
    .) {
        cmd="v $0";
        eval "$cmd"
        exit 0
    } ;;
    h|V) cmd="tm -d sph \"m u $page\"" ;;
    v|H) cmd="tm -d spv \"m u $page\"" ;;
    n|w) cmd="tm -d nw \"m u $page\"" ;;
    p) {
        eval "tm -d rs \"m u $page\""
        exit 0
    } ;;
    e) {
        eval "tm -d rs \"eman $page\""
        exit 0
    } ;;
    W) {
        eval "tm -d rs \"woman $page\""
        exit 0
    } ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty

set -m
bash -c "sleep 0.1; $cmd" & disown