#!/bin/bash
export TTY

# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
r  restart
HEREDOC

echo "$0" | udl
echo "$options" | mnm

read -n1 d
# clear


case "$d" in
    .) cmd="v $0" ;;
    r) cmd="ssh rbp \"sudo shutdown -r now\"" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"
