#!/bin/bash
export TTY

# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started alreaddy.

read -r -d '' options <<HEREDOC
d current directory
t tmux capture
g git url
f tmux capture and filter 
HEREDOC

echo "$0" | udl
echo "$@" | ns | udl
echo "$options"

fp="$1"
dir="$(p "$fp" | u dn)"
cd "$dir"
export CWD="$1"

read -n1 d
# clear

case "$d" in
    d) cmd="pwd | xc -i -n" ;;
    t) cmd="tm -te -d capture -clean -history" ;;
    g) { cmd="git config --get remote.origin.url | xc -n -i -"; }; ;;
    f) cmd="tm cap-pane | tm -f -S -tout sph -noerror \"f filter-with-fzf\"" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"
