#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
p  mosh-or-ssh pipeline
i  mosh-or-ssh si1
d  sh-remote-dir
k  sh-kubectl
HEREDOC

echo "$0" | udl
echo "$options" | mnm

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    p) cmd="nvt mosh-or-ssh pipeline" ;;
    i) cmd="nvt mosh-or-ssh si1" ;;
    d) cmd="sh-remote-dir" ;;
    k) cmd="sh-kubectl" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"