#!/bin/bash
export TTY

clear
# exec 1> >(mnm)

# I should turn this entire script into an elisp hydra.
# Although that would require that emacs has been started already.

read -r -d '' options <<HEREDOC
.  EDIT
1  mosh instance-1
HEREDOC

echo "$0" | udl
echo "$options" | mnm

read -n1 d
# clear

case "$d" in
    .) cmd="v $0" ;;
    1) cmd="mosh instance-1" ;;
esac
echo
echo "$cmd"

# exec </dev/tty
# exec 1> /dev/tty
eval "$cmd"