#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ]
}

last_arg="${@: -1}"
fp="$last_arg"
shift

if { ! stdin_exists; } && test -n "$fp" && test -f "$fp"; then
    cmd_prefix+="cat $(aqf "$fp") | "
fi

CMD="$(cmd "$@")"
: ${CMD:="-n \"s/.* /\U&/ip\""}

# s chomp | rtcmd "+/\(\\<sed\\>\( -[^ ]\+\)* [^-]\)\@<=." -E "sed $CMD | vi -"

# s chomp | eval "rtcmd ++sed sed $CMD"

cmdname=sed

if stdin_exists; then
    s chomp | rtcmd ++$cmdname -E "$cmdname $CMD | vi -"
else
    rtcmd ++$cmdname -E "$cmd_prefix $cmdname $CMD | vi -"
fi
