#!/bin/bash

start_skype() {
    printf -- "%s\n" "Loading skype..."

    exec &>/dev/null

    # To get skype to remain open, need to create a tty for it and use bash.
    # Also, the sleep is necessary for skype to notice it has a real tty
    # before it is destroyed.
    # to keep the tty alive
    bash -ic "skypeforlinux $@; bash" & disown; sleep 1

    return 0
}

cmd="$1"
case "$cmd" in
    -k|k)
        {
            exec &>/dev/null

            killall skypeforlinux
        }
    ;;
    *)
        start_skype
esac