#!/bin/bash
export TTY
# shopt -s nullglob # use for 'for' loops but not for 'ls', 'grep'

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -t) {
        session_name="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: ${session_name:="localhost"}

tmux attach -t "${session_name}:"
