#!/bin/bash
export TTY

CMD="$(
for (( i = 1; i < $#; i++ )); do
    eval ARG=\${$i}
    printf -- "%s" "$ARG" | q
    printf ' '
done
eval ARG=\${$i}
printf -- "%s" "$ARG" | q
)"

# echo "$CMD" | tmless
# echo "tm -f -S -tout nw -fa $CMD" | tmless
eval "tm -f -S -tout nw -fa $CMD"
