#!/bin/bash
export TTY

# https://codelingo.slack.com/archives/GAYUSPKPU/p1540415876000200
# https://codelingo.slack.com/messages/GAYUSPKPU/convo/GAYUSPKPU-1540415876.000200/

sed 's=^\(.*/\)archives/\([^/]\+\)/p\([0-9]\{10\}\)\([0-9]\{6\}\)$=\1messages/\2/convo/\2-\3.\4/='