#!/bin/bash
export TTY

stdin_exists() {
    ! [ -t 0 ]
}

if stdin_exists; then
    awk1 | while IFS=$'\n' read -r line; do
        /usr/bin/urlencode -d "$line"
    done
else
    /usr/bin/urlencode -d "$@"
fi

# : "${*//+/ }"; echo -e "${_//%/\\x}";