#!/bin/bash
export TTY

( hs "$(basename "$0")" "$@" "<==" "$(ps -o comm= $PPID)" 0</dev/null ) &>/dev/null

# flatten out the query
query="$@"

code="WolframAlpha[$(aqf "$query"), $(aqf "ShortAnswer")]"

printf -- "%s" "$code" | ds -s wa-last-query 

ci mma "$code"
