#!/bin/bash
export TTY

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    "") { shift; }; ;;
    -E) {
        thecmd="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

if test -n "$thecmd"; then
    awk1 | while IFS=$'\n' read -r line; do
        printf -- "%s\n" "$line" | eval "$thecmd"
    done
else
    awk1 | while IFS=$'\n' read -r line; do
        printf -- "%s\n" "$line" | "$@"
    done
fi
