#!/bin/bash
export TTY

# Execute this?

while [ $# -gt 0 ]; do opt="$1"; case "$opt" in
    -E) {
        CMD="$2"
        shift
        shift
    }
    ;;

    *) break;
esac; done

: ${CMD:="$(cmd "$@")"}

yn "execute this?\n\n$CMD" && eval "$CMD"
